CREATE SCHEMA ORDER_DB;

DROP TABLE IF EXISTS ORDER_DB.ORDER_LINES;
DROP TABLE IF EXISTS ORDER_DB.ORDERS;

CREATE TABLE ORDER_DB.orders(
  ID UUID NOT NULL,
  CUSTOMER_ID VARCHAR(100) NOT NULL,
  DELIVERY_PRICE DECIMAL,
  ORDER_DISCOUNT_PRICE DECIMAL,
  LAST_UPDATE_DATE timestamp without time zone DEFAULT now(),
  CREATED_DATE timestamp without time zone DEFAULT now(),
  CONSTRAINT order_id PRIMARY KEY(ID)
);

CREATE TABLE ORDER_DB.ORDER_LINES(
  ID UUID NOT NULL,
  PRODUCT_ID VARCHAR(100) NOT NULL,
  QUANTITY INTEGER NOT NULL,
  UNIT_PRICE DECIMAL NOT NULL,
  DISCOUNT_PRICE DECIMAL,
  ORDER_ID UUID,
  LAST_UPDATE_DATE timestamp without time zone DEFAULT now(),
  CREATED_DATE timestamp without time zone DEFAULT now(),
  CONSTRAINT order_line_id PRIMARY KEY (id),
  CONSTRAINT fk_order_id FOREIGN KEY(ORDER_ID)
	REFERENCES ORDER_DB.ORDERS(ID) MATCH SIMPLE
	ON UPDATE NO ACTION
	ON DELETE NO ACTION  
);

