INSERT INTO ORDER_DB.ORDERS(CUSTOMER_ID) VALUES (1);
INSERT INTO ORDER_DB.ORDERS(CUSTOMER_ID) VALUES (1);
INSERT INTO ORDER_DB.ORDERS(CUSTOMER_ID) VALUES (1);
INSERT INTO ORDER_DB.ORDERS(CUSTOMER_ID) VALUES (2);
INSERT INTO ORDER_DB.ORDERS(CUSTOMER_ID) VALUES (2);

INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 1, 1);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 12, 2);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 2, 2);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 3, 3);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 4, 4);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 5, 5);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 15, 5);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 25, 5);
INSERT INTO ORDER_DB.ORDER_LINES(PRODUCT_ID, QUANTITY, ORDER_ID) VALUES (1, 35, 5);