CREATE SCHEMA ORDER_DB;

CREATE TABLE ORDER_DB.ORDERS(
  ID BIGSERIAL PRIMARY KEY,
  CUSTOMER_ID VARCHAR(64) NOT NULL,
  LAST_UPDATE timestamp without time zone not null DEFAULT now(),
  CREATED_DATE timestamp without time zone not null DEFAULT now()
);

CREATE TABLE ORDER_DB.ORDER_LINES(
  ID BIGSERIAL PRIMARY KEY,
  PRODUCT_ID VARCHAR(64) NOT NULL,
  QUANTITY INTEGER NOT NULL,
  ORDER_ID BIGINT NOT NULL,
  LAST_UPDATE timestamp without time zone not null DEFAULT now(),
  CREATED_DATE timestamp without time zone not null DEFAULT now()
);

ALTER TABLE ORDER_DB.ORDER_LINES ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDER_DB.ORDERS(ID);
