spring:
  application:
    name: notifier
  mail:
    host: smtp.gmail.com
    port: 587
    username: tatsiana.ramanchuk@gmail.com
    password: agnzpvzsdhghjjdk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "com.example.kafka.dto.OrderDto"
        "[spring.json.trusted.packages]": "com.example.kafka.dto.*"
    security:
      protocol: SASL_PLAINTEXT
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="order_reader" password="order_reader_password";