spring:
  application:
    name: order-aggregator
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: localhost
resilience4j:
  circuitbreaker:
    instances:
      remittance-service:
        failureRateThreshold: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      remittance-service:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      remittance-service:
        timeoutDuration: 5s
        cancelRunningFuture: true