spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8081
          predicates:
            - Path=/v1/customers/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/products/**
        - id: order_route
          uri: http://localhost:8083
          predicates:
            - Path=/v1/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: localhost