spring:
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8081
          predicates:
            - Path=/v1/customers/**
        - id: product_route
          uri: http://localhost:8082
          predicates:
            - Path=/v1/products/**
        - id: order_route
          uri: http://localhost:8083
          predicates:
            - Path=/v1/orders/**